# Generated by Django 3.1.1 on 2020-12-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-updated',)},
        ),
    ]
